"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { RefreshCw } from "lucide-react"

// Mock data - would be fetched from API in real implementation
const mockScenarios = [
  {
    id: 1,
    name: "Blog Introduction",
    prompt: "Write an introduction for a blog post about artificial intelligence trends in 2025.",
  },
  {
    id: 2,
    name: "Tweet Thread",
    prompt: "Create a tweet thread (3 tweets) about the importance of cybersecurity for small businesses.",
  },
  {
    id: 3,
    name: "Product Review",
    prompt: "Write a brief review of the latest smartphone technology.",
  },
  {
    id: 4,
    name: "Industry Analysis",
    prompt: "Provide a short analysis of how blockchain is changing the finance industry.",
  },
  {
    id: 5,
    name: "Tutorial Introduction",
    prompt: "Write an introduction for a tutorial on getting started with machine learning.",
  },
]

// Mock responses - would be generated by API in real implementation
const mockResponses = {
  1: "# AI Trends Shaping Our Future in 2025\n\nAs we navigate through 2025, artificial intelligence continues to evolve at a breathtaking pace, transforming industries and redefining what's possible. From generative AI that creates indistinguishable-from-human content to edge AI that brings intelligence directly to devices, the landscape is rich with innovation. In this post, we'll explore the five key AI trends that are not just emerging but actively reshaping our technological ecosystem. Whether you're a tech enthusiast, business leader, or simply curious about where AI is headed, understanding these trends will provide valuable insight into our collective digital future.",
  2: "1/3 Small businesses are increasingly becoming targets for cybercriminals, with 43% of attacks now aimed at SMBs. Why? Because they often lack robust security infrastructure while still handling valuable customer data and financial information.\n\n2/3 The cost of a data breach for small businesses isn't just financial—it's existential. 60% of small companies go out of business within 6 months of a significant cyber attack. Implementing even basic security measures can reduce this risk by over 80%.\n\n3/3 Start with these essentials: 1) Employee security training, 2) Multi-factor authentication, 3) Regular software updates, 4) Data backups, and 5) A basic incident response plan. These five steps alone can prevent the majority of common attacks targeting small businesses.",
  3: "The XYZ Pro 15 represents a significant leap forward in smartphone technology, balancing cutting-edge features with practical usability. Its standout neural processing unit delivers AI capabilities that actually enhance daily use rather than serving as mere gimmicks. Battery life finally matches the marketing claims, easily lasting a full day of heavy use. Camera quality in low-light conditions has improved dramatically, though still slightly behind the market leader. The redesigned interface prioritizes one-handed operation—a thoughtful touch in an era of increasingly unwieldy devices. At this price point, it delivers exceptional value for both tech enthusiasts and everyday users looking for a device that will remain relevant for years to come.",
  4: "Blockchain technology is fundamentally restructuring finance by addressing its core inefficiencies. Traditional banking processes that once took days now complete in minutes through smart contracts, reducing settlement times by 96% and cutting operational costs by an estimated $27 billion annually across the industry. Beyond efficiency, blockchain is democratizing financial access—22% of previously unbanked individuals now participate in the financial system through blockchain-based services. Regulatory frameworks are finally catching up, with 37 countries implementing comprehensive crypto legislation in the past year alone. While challenges remain in scalability and energy consumption, the finance sector's blockchain transformation has moved decisively from experimental to operational, with 84% of major financial institutions now incorporating the technology into their strategic roadmaps.",
  5: "# Getting Started with Machine Learning: A Practical Guide\n\nMachine learning might seem like a complex field reserved for mathematicians and computer scientists, but the reality is far more accessible. With today's tools and resources, anyone with curiosity and persistence can begin building ML models that solve real problems. This tutorial will guide you through the essential concepts, tools, and techniques you need to start your machine learning journey—no PhD required.\n\nWe'll focus on practical applications rather than theoretical complexity, using Python and popular libraries that make implementation straightforward. By the end of this guide, you'll have built your first predictive model and gained the confidence to tackle more advanced projects. Let's demystify machine learning together and put this powerful technology to work for you."
}

export function PersonaPreview() {
  const [selectedScenario, setSelectedScenario] = useState<string>("1")
  const [customPrompt, setCustomPrompt] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [response, setResponse] = useState("")
  
  const handleScenarioChange = (value: string) => {
    setSelectedScenario(value)
    setCustomPrompt("")
    setResponse(mockResponses[value as keyof typeof mockResponses] || "")
  }
  
  const handleCustomPromptChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setCustomPrompt(e.target.value)
    setResponse("")
  }
  
  const generateResponse = () => {
    setIsGenerating(true)
    
    // Simulate API call delay
    setTimeout(() => {
      if (customPrompt) {
        // For custom prompts, generate a placeholder response
        setResponse("This is a simulated response to your custom prompt. In a real implementation, this would be generated by calling the AI with your persona configuration applied.")
      } else {
        // For predefined scenarios, use the mock responses
        setResponse(mockResponses[selectedScenario as keyof typeof mockResponses] || "")
      }
      setIsGenerating(false)
    }, 1500)
  }
  
  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <Label htmlFor="scenario">Select a Scenario</Label>
        <Select
          value={selectedScenario}
          onValueChange={handleScenarioChange}
        >
          <SelectTrigger id="scenario">
            <SelectValue placeholder="Select a scenario" />
          </SelectTrigger>
          <SelectContent>
            {mockScenarios.map((scenario) => (
              <SelectItem key={scenario.id} value={scenario.id.toString()}>
                {scenario.name}
              </SelectItem>
            ))}
            <SelectItem value="custom">Custom Prompt</SelectItem>
          </SelectContent>
        </Select>
      </div>
      
      {selectedScenario === "custom" ? (
        <div className="space-y-2">
          <Label htmlFor="customPrompt">Custom Prompt</Label>
          <Textarea
            id="customPrompt"
            placeholder="Enter your custom prompt here..."
            value={customPrompt}
            onChange={handleCustomPromptChange}
            rows={3}
          />
        </div>
      ) : (
        <div className="space-y-2">
          <Label>Prompt</Label>
          <div className="rounded-md border p-3 bg-muted/50">
            {mockScenarios.find(s => s.id.toString() === selectedScenario)?.prompt || ""}
          </div>
        </div>
      )}
      
      <div className="flex justify-end">
        <Button 
          onClick={generateResponse} 
          disabled={isGenerating || (selectedScenario === "custom" && !customPrompt)}
        >
          {isGenerating ? (
            <>
              <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            "Generate Response"
          )}
        </Button>
      </div>
      
      {response && (
        <div className="space-y-2">
          <Label>Generated Response</Label>
          <Card>
            <CardContent className="p-4 whitespace-pre-wrap font-medium">
              {response}
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  )
}
